---
title: "Statistical Inference Project"
author: "Xinli"
date: "May 19, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
1. Show the sample mean and compare it to the theoretical mean of the distribution.
```{r cars}
set.seed(2016)
lambda=0.2
n=40
simat <- replicate(1000, rexp(n, lambda))
means <- colMeans(simat)
# simulated mean
mean(means)
```

```{r}
tmean <- 1/lambda
tmean
```
Theoretical mean is 5

2. Show how variable the sample is (via variance) and compare it to the theoretical variance of the distribution.
```{r}
#simulated variance
svar <- var(means)
svar
```

```{r}
#Theoretial variance 
tvar <- (1/lambda)^2/n
tvar
```

3. Show that the distribution is approximately normal.
```{r}
hist(means, breaks = 50, xlab="Mean", main = "Comparing to Normal Distribution")
xnorm <- seq(min(means),max(means), length=1000)
ynorm <- dnorm(xnorm, mean=1/lambda, sd=1/lambda/sqrt(n))
lines(xnorm, ynorm*100)
```
The figure above shows that the distribution is approximately normal.
